namespace AppAutomation.Abstractions;

/// <summary>
/// Defines a UI control's locator information for runtime resolution.
/// </summary>
/// <param name="PropertyName">The name of the property on the page class.</param>
/// <param name="ControlType">The type of UI control.</param>
/// <param name="LocatorValue">The value used to locate the control (automation ID or name).</param>
/// <param name="LocatorKind">The locator strategy. Defaults to <see cref="UiLocatorKind.AutomationId"/>.</param>
/// <param name="FallbackToName">Whether to fall back to name-based lookup. Defaults to <see langword="true"/>.</param>
public sealed record UiControlDefinition(
    string PropertyName,
    UiControlType ControlType,
    string LocatorValue,
    UiLocatorKind LocatorKind = UiLocatorKind.AutomationId,
    bool FallbackToName = true);

/// <summary>
/// Defines a page's control manifest for discovery and documentation.
/// </summary>
/// <param name="PageTypeFullName">The fully qualified type name of the page class.</param>
/// <param name="PageName">A human-readable name for the page.</param>
/// <param name="Controls">The collection of control definitions on this page.</param>
public sealed record UiPageDefinition(
    string PageTypeFullName,
    string PageName,
    IReadOnlyList<UiControlDefinition> Controls);

/// <summary>
/// A complete manifest of all UI locators in an assembly.
/// </summary>
/// <remarks>
/// This manifest is generated by the source generator and can be used for:
/// <list type="bullet">
/// <item>Documentation generation</item>
/// <item>Test discovery</item>
/// <item>Tooling integration</item>
/// </list>
/// </remarks>
/// <param name="ContractVersion">The version of the manifest contract format.</param>
/// <param name="AssemblyName">The name of the assembly containing the page definitions.</param>
/// <param name="Pages">The collection of page definitions in the assembly.</param>
public sealed record UiLocatorManifest(
    string ContractVersion,
    string AssemblyName,
    IReadOnlyList<UiPageDefinition> Pages);

/// <summary>
/// Provides access to the UI locator manifest for an assembly.
/// </summary>
/// <remarks>
/// Implement this interface to expose the source-generated manifest.
/// The source generator creates an implementation automatically.
/// </remarks>
public interface IUiLocatorManifestProvider
{
    /// <summary>
    /// Gets the UI locator manifest for the assembly.
    /// </summary>
    /// <returns>The <see cref="UiLocatorManifest"/> containing all page and control definitions.</returns>
    UiLocatorManifest GetManifest();
}
